language: c
sudo: false # only for faster builds
compiler: gcc
branches:
  only:
    - master
notifications: # 성공 실패 여부 알림 
  email:
    recipients:
      - robin@inzent.com
script:
  - gcc --coverage -O0 testmain.c -o testmain
  - ./testmain
  - gcov testmain.c

